CREATE DATABASE RecensioniCulinarie;

USE RecensioniCulinarie;

CREATE TABLE Critico(
	Id INT AUTO_INCREMENT PRIMARY KEY,
	Nome VARCHAR(20) NOT NULL,
	Cognome VARCHAR(20) NOT NULL,
	DataN DATE NOT NULL,
	Curriculum TEXT NOT NULL,
	Foto VARCHAR(2000) NOT NULL,
	LinkTwitter VARCHAR(2000) NOT NULL
);

CREATE TABLE Ristorante (
	Id INT AUTO_INCREMENT PRIMARY KEY,
	Nome VARCHAR(20) NOT NULL,
	Tipologia VARCHAR(20) NOT NULL,
	Via VARCHAR(20) NOT NULL,
	Civico VARCHAR(20) NOT NULL,
	Prenotazione BOOL NOT NULL,
	Parcheggio BOOL NOT NULL,
	Animali BOOL NOT NULL,
	NStelleM INT
);

CREATE TABLE Recensione (
	Id INT AUTO_INCREMENT PRIMARY KEY,
	Titolo VARCHAR(40) NOT NULL,
	Testo VARCHAR(5000) NOT NULL, 
	DataP DATE NOT NULL,
	VotoL DECIMAL(3,1) NOT NULL,
	VotoS DECIMAL(3,1) NOT NULL,
	VotoM DECIMAL(3,1) NOT NULL,
	VotoC DECIMAL(3,1) NOT NULL,
	CodCritico INT NOT NULL,
	CodRistorante INT NOT NULL,
	FOREIGN KEY (CodCritico) REFERENCES Critico(Id),
	FOREIGN KEY (CodRistorante) REFERENCES Ristorante(Id)  
);

